version: 2.1
description: "Changing the service images with jira story."

parameters:
  jira-story:
    type: string
    description: "Jira story ticket No"
    default: latest

steps:
  - run:
      environment:
        JIRA_STORY: <<parameters.jira-story>>
      name: Get the jira story if available
      command: |
        echo YOUR JIRA STORY IS $JIRA_STORY
        echo TEST TEST
        
        

